// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbwbnjcebxxjoiqlofso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtid2JuamNlYnh4am9pcWxvZnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODU4NjksImV4cCI6MjA2MjM2MTg2OX0.Vj-r37Q-AAHTUZ0IDDgrdrQlOtjGNeEQ8sBNtT7Jsec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);